// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC71HKrjhFQsxghKyLkL8TbB2ewCQISkKo',
    appId: '1:872208755472:web:277ba8f544db3c5f711395',
    messagingSenderId: '872208755472',
    projectId: 'scorplingua',
    authDomain: 'scorplingua.firebaseapp.com',
    storageBucket: 'scorplingua.firebasestorage.app',
    measurementId: 'G-431J2SMXPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-KTqAKMjR6d9mZoFPR7ipruFHnBsQkAU',
    appId: '1:872208755472:android:c12d56e5d2711f62711395',
    messagingSenderId: '872208755472',
    projectId: 'scorplingua',
    storageBucket: 'scorplingua.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANEYHksqqt0gz_JImAyudaPjRjTEZujDM',
    appId: '1:872208755472:ios:650a67ce463882ab711395',
    messagingSenderId: '872208755472',
    projectId: 'scorplingua',
    storageBucket: 'scorplingua.firebasestorage.app',
    iosClientId: '872208755472-v6iu30u4kvmmocf822v7b180bff7etab.apps.googleusercontent.com',
    iosBundleId: 'com.example.scorplingua',
  );
}
